"""add message and proposed_dates to applications

Revision ID: 204fcc665ec0
Revises: 138237419714
Create Date: 2026-05-11 16:08:51.102498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204fcc665ec0'
down_revision: Union[str, Sequence[str], None] = '138237419714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('proposed_dates', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'proposed_dates')
    op.drop_column('applications', 'message')
    # ### end Alembic commands ###
